### PR TITLE
Update Hindi Translations and credits

### PR DESCRIPTION
**Pull request by hemish04082005**
I am new to translating applications and I hope that I did it correctly! Please mention mistakes done by me (if any).
I have translated 'Dialect' app to Hindi (an Indian language) and I have correctly adapted it to local speakings and what people understand (i mean if you translate the interface of this app line by line through some translating service, some lines will not make any sense, i have taken care of it so that translations make sense and are readable by public)
I had done this stuff on weblate and my translations were automatically pushed by weblate but here, in this pull request i am adding my account to credits mentions.

### CODE REVIEW

**Comment by fushinari** [comment]
Cool! Should be fine, but this is also kind of a test because we haven't used direct pull requests since setting up weblate. So please bear with me if something goes wrong and don't worry too much XD

**Comment by fushinari** [comment]
That went well :)

**Comment by fushinari** [comment]
Thanks for your work! Really appreciate it, especially as an Indian XD

**Comment by hemish04082005** [comment]
Yeah, i noticed that only 40 percent or even luss stuff of GNOME is translated to Hindi! I just today learnt about gettext module. Simultaenously i got to know about apps.gnome.org which is recently established and got this dialect app from here and found out that it doesn't have hindi translation. So, i spent my 1 hour to public work hoping it would make linux more accessible.
and I may be translate this to Punjabi language also as i know it too. Whenever, i would get time, i would do that too.
These are the only 2 indian languages that i know ( i belong to north india)

**Comment by fushinari** [comment]
Yes, sadly, Indic translations tend to be poor in open source. Indians are very reluctant to do unpaid work (understandably, since our quality of life is also relatively low, making unpaid work less feasible). Really glad to see work like this still happening :)

**Pull request merged**
